inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - lib/tasks/*
    - lib/traject/vatican_iiif_config.rb
    - lib/traject/annotation_config.rb
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/LineLength:
  Exclude:
    - lib/traject/vatican_iiif_config.rb
    - spec/features/vatican_iiif_resource_integration_spec.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 5
