dist: trusty
addons:
  chrome: stable
notifications:
  email: false

rvm:
  - 2.5.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - gem update --system
  - gem install bundler
  - google-chrome-stable --headless --no-sandbox --disable-gpu --remote-debugging-port=9222 http://localhost &
  - nvm install node
  - node -v
  - npm i

before_script:
  - bin/rails assets:precompile
  - bin/rails db:test:prepare

sudo: false
language: ruby
cache: bundler

jdk: oraclejdk8
